name: Run Lithia 1 Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy msal requests pyodbc

    - name: Run scraper
      env:
        AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
        AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
        AZURE_SQL_TABLE_NAME: ${{ secrets.AZURE_SQL_TABLE_NAME }}

        AZURE_SP_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
        AZURE_SP_AUTHORITY: ${{ secrets.AZURE_SP_AUTHORITY }} 
        AZURE_SP_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}        
      run: python Lithia.py
      # working-directory: ${{ github.workspace }}
