name: Run Lithia 1 Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy msal requests pyodbc azure-identity azure-mgmt-sql

    - name: Run scraper
      env:
        AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
        AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
        AZURE_SQL_TABLE_NAME: ${{ secrets.AZURE_SQL_TABLE_NAME }}

        AZURE_SP_CLIENT_ID: ${{ secrets.AZURE_SP_CLIENT_ID }}
        AZURE_SP_AUTHORITY: ${{ secrets.AZURE_SP_AUTHORITY }} 
        AZURE_SP_CLIENT_SECRET: ${{ secrets.AZURE_SP_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_RESOURCE_GROUP_NAME: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
        AZURE_SQLSERVER_RESOURCE_NAME: ${{ secrets.AZURE_SQLSERVER_RESOURCE_NAME }}
      run: python Lithia.py
      # working-directory: ${{ github.workspace }}
