name: Run Lithia 1 Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas sqlalchemy pypyodbc requests

    - name: Run scraper
      env:
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SERVER_NAME: ${{ secrets.SERVER_NAME }}
        TABLE_NAME: ${{ secrets.TABLE_NAME }}
        USERNAME: ${{ secrets.USERNAME }}        
      run: python Lithia.py
      # working-directory: ${{ github.workspace }}
